# Generated by Django 2.1.2 on 2018-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussions',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
