# Generated by Django 2.1.2 on 2018-12-05 22:00

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discussions_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussions',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True)]},
        ),
    ]
