# Generated by Django 2.1.2 on 2018-11-27 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181121_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='realname',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_by',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Status'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='is_accepted',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='req_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='req_to',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
