# Generated by Django 2.1.2 on 2018-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181127_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
