# Generated by Django 2.1.2 on 2018-12-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181122_0003'),
        ('user', '0004_auto_20181127_1811'),
    ]

    operations = [
    ]
