# Generated by Django 2.1.2 on 2018-12-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181203_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussioncomments',
            name='comment_by',
        ),
        migrations.RemoveField(
            model_name='discussioncomments',
            name='discussion_id',
        ),
        migrations.RemoveField(
            model_name='discussions',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='DiscussionComments',
        ),
        migrations.DeleteModel(
            name='Discussions',
        ),
    ]
