# Generated by Django 2.1.2 on 2018-12-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181205_2341'),
        ('user', '0007_auto_20181203_1336'),
        ('user', '0005_auto_20181203_2257'),
    ]

    operations = [
    ]
