# Generated by Django 2.1.2 on 2018-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20181206_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='real_name',
            new_name='realname',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
